name: Docker deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Composer ${{ matrix.composer-version }}
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    strategy:
    steps:
      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Generate metadata
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eliashaeussler/cache-warmup
          flavor: latest=true
          tags: type=semver,pattern={{version}}

      # Prepare build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login at Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
