name: Release
on:
  push:
    tags:
      - '*'

jobs:
  phar:
    name: Compile PHAR
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      # Compile PHAR
      - name: Install box
        run: composer global require --dev --no-progress humbug/box
      - name: Install Composer dependencies
        run: composer update --no-progress
      - name: Compile PHAR
        run: box compile --with-docker

      # Upload compiled PHAR as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: phar
          path: |
            .build/cache-warmup.phar
            Dockerfile

  docker:
    name: Docker deploy
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    needs: phar
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Download PHAR and Dockerfile
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: phar

      # Generate metadata
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eliashaeussler/cache-warmup
          flavor: latest=true
          tags: type=semver,pattern={{version}}

      # Prepare build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login at Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  # Job: Create release
  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    needs: phar
    steps:
      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Download PHAR
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: phar

      # Create release
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            .build/cache-warmup.phar
